import type { Cesacion } from "../../../../models/Cesaciones";
import { toISODateFlex } from "../../../../utils/Date";

export function createEmptyCesacion(reportadoPor: string): Cesacion {
  return {
    Cargo: "",
    Celular: "",
    Correoelectronico: "",
    FechaIngreso: null,
    FechaLimiteDocumentos: null,
    FechaSalidaCesacion: null,
    Jefedezona: "",
    Nombre: "",
    Temporal: "",
    Tienda: "",
    Title: "",
    Reportadopor: reportadoPor,
    Empresaalaquepertenece: "",
    Fechaenlaquesereporta: toISODateFlex(new Date()),
    TipoDoc: "",
    Departamento: "",
    Ciudad: "",
    Niveldecargo: "",
    CargoCritico: "",
    Dependencia: "",
    CodigoCC: "",
    DescripcionCC: "",
    CodigoCO: "",
    DescripcionCO: "",
    CodigoUN: "",
    DescripcionUN: "",
    Salario: "",
    SalarioTexto: "",
    auxConectividadTexto: "",
    auxConectividadValor: "",
    Pertenecealmodelo: false,
    GrupoCVE: "",
    PresupuestaVentas: "",
    Autonomia: "",
    ImpactoCliente: "",
    contribucionEstrategia: "",
    Promedio: "",
    Estado: "En proceso",
    direccionResidencia: "",
    CanceladoPor: "",
    RazonCancelacion: "",
    FechaExamenesMedicos: null
  };
}